<?xml version="1.0" encoding="utf-8"?><Database Name="DuLieu" Class="DBCustomersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-INNQGHI\SQLEXPRESS01;Initial Catalog=DuLieu;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DuLieuConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblKhach" Member="tblKhaches">
    <Type Name="tblKhach">
      <Column Name="Makhach" Type="System.String" DbType="Char(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhach" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>